version: '3'

services:
  api:
    build: ./api
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      DATABASE_URL: postgres://mediumcloneuser:8848@postgres:5432/mediumclone
      PORT: 80
    depends_on:
      - postgres

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: mediumcloneuser
      POSTGRES_PASSWORD: 8848
      POSTGRES_DB: mediumclone
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "35000:5432"